version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: salon_user
      POSTGRES_PASSWORD: salon_password
      POSTGRES_DB: salon_connect
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U salon_user -d salon_connect"]
      interval: 5s
      timeout: 5s
      retries: 5

  # API Server
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://salon_user:salon_password@postgres:5432/salon_connect?schema=public
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      NODE_ENV: development
      PORT: 5000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./apps/api:/app/apps/api
      - ./packages:/app/packages
      - /app/node_modules
    command: npm run dev --workspace=apps/api

  # Frontend (for development)
  web:
    build:
      context: ./apps/web
      dockerfile: ../../Dockerfile.web
    ports:
      - "3000:3000"
    environment:
      API_URL: http://api:5000/api
      NODE_ENV: development
    depends_on:
      - api
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data: