# Render Blueprint: SalonConnect Platform
# Beauty and salon booking platform with social features

services:
  # API Server
  - type: web
    name: salon-connect-api
    runtime: node
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: npm start --workspace=apps/api
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: salon-connect-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ALLOWED_ORIGINS
        fromService:
          name: salon-connect-web
          type: web
          envVarKey: RENDER_EXTERNAL_URL

  # Static Frontend (Next.js export)
  - type: web
    name: salon-connect-web
    runtime: static
    plan: free
    buildCommand: npm install --include=dev && npm run build --workspace=apps/web
    staticPublishPath: apps/web/out
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: salon-connect-api
          type: web
          envVarKey: RENDER_EXTERNAL_URL

databases:
  - name: salon-connect-db
    databaseName: salon_connect
    user: salon_user
    plan: free