# Render Blueprint: SalonConnect Platform
# Beauty and salon booking platform with social features

services:
  # API Server
  - type: web
    name: salon-connect-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: salon-connect-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  # Frontend (Static Site)
  - type: static
    name: salon-connect-web
    buildCommand: npm install && npm run build --workspace=apps/web
    publishPath: ./apps/web/out
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://salon-connect-api.onrender.com/api
      - key: NODE_ENV
        value: production

databases:
  - name: salon-connect-db
    databaseName: salon_connect
    user: salon_user
    plan: free